/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Moklet
 */
public class penarikan1 extends javax.swing.JFrame {
    int s; 
    int bal;
    int a;
    int hasil;
    int saldo1;
    
    public penarikan1() {
        initComponents();
        
        Home ss = new Home() ;
        saldo1 = ss.getsaldo() ;
          
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tarik = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        tarik2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Jumlah uang yang ingin diambil ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 0, 170, 60);
        getContentPane().add(tarik);
        tarik.setBounds(80, 60, 230, 50);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(210, 170, 100, 30);

        tarik2.setText("Tarik Tunai");
        tarik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarik2ActionPerformed(evt);
            }
        });
        getContentPane().add(tarik2);
        tarik2.setBounds(60, 170, 100, 30);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        Home a = new Home();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void tarik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarik2ActionPerformed
        
        
        getsaldo();
        a = Integer.parseInt(tarik.getText());
        String a1 = tarik.getText() ;
    
        if(a < saldo)
        {
        if(a < 50000){
            JOptionPane.showMessageDialog(null, "Penarikan tunai minimal Rp. 50000");
        }else
        {
            
            
            JOptionPane.showMessageDialog(null, "berhasil");
            hasil = saldo1 -= a ;
            this.dispose();
            new Home().setVisible(true);
        }
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Saldo anda kurang dari yang anda tarik");   
            
            
        }
    }//GEN-LAST:event_tarik2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penarikan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penarikan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penarikan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penarikan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penarikan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tarik;
    private javax.swing.JButton tarik2;
    // End of variables declaration//GEN-END:variables

    int saldo = 500000;
    public int getsaldo(){
        return saldo;
    }
}
