/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Moklet
 */
public class setor1 extends javax.swing.JFrame {

     int s; 
    int bal;
    int a;
    int hasil;
    int saldo1;
    /**
     * Creates new form setor1
     */
    public setor1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hayo = new javax.swing.JTextField();
        hayo2 = new javax.swing.JButton();
        hayo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Jumlah yang ingin di setor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 170, 50);
        getContentPane().add(hayo);
        hayo.setBounds(100, 70, 200, 50);

        hayo2.setText("CANCEL");
        getContentPane().add(hayo2);
        hayo2.setBounds(220, 160, 100, 40);

        hayo1.setText("SETOR");
        hayo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hayo1ActionPerformed(evt);
            }
        });
        getContentPane().add(hayo1);
        hayo1.setBounds(70, 160, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hayo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hayo1ActionPerformed
       
        getsaldo();
    
        if(a < 50000){
            JOptionPane.showMessageDialog(null, "Jumlah setor tunai minimal Rp. 50000");
        }else
        {
            
            
            JOptionPane.showMessageDialog(null, "berhasil");
            hasil = saldo1 -= a ;
            this.dispose();
            new Home().setVisible(true);
        }
    }
    
     

    int saldo = 500000;
    public int getsaldo(){
        return saldo;
    }
    }//GEN-LAST:event_hayo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setor1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hayo;
    private javax.swing.JButton hayo1;
    private javax.swing.JButton hayo2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


 
