/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Moklet
 */
public class transfer1 extends javax.swing.JFrame {
    int s; 
    int bal;
    int a ;
    int b;
    int hasil;
    
    
    int saldo1 ;
    
    
    /**
     * Creates new form transfer1
     */
    public transfer1() {
        initComponents();
        Home ss = new Home() ;
        saldo1 = ss.getsaldo() ;
          
        JOptionPane.showMessageDialog(null, "ds"+saldo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        norek = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Masukkan Nomer Rekening");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 190, 50);

        norek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norekActionPerformed(evt);
            }
        });
        getContentPane().add(norek);
        norek.setBounds(170, 60, 220, 40);

        jLabel2.setText("Masukkan Jumlah Uang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 150, 50);

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah);
        jumlah.setBounds(170, 110, 220, 40);

        jButton1.setText("Transfer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 210, 100, 30);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(210, 210, 100, 30);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 100);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        Home a = new Home(); 
       a.setVisible(true);
       dispose();
        
        
    }//GEN-LAST:event_cancelActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        
    }//GEN-LAST:event_jumlahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        
        String a2 = jumlah.getText().toString();
        String a1 = norek.getText().toString() ;
  
        
        
        if(a1.length() != 12)
        {
            JOptionPane.showMessageDialog(null, "Digit tidak lengkap, Maximal 12 digit");   
           a = Integer.parseInt(a1);
            b = Integer.parseInt(a2);

        }   
        if( b < saldo1){
        if( b < 50000) {
            JOptionPane.showMessageDialog(null,"Transaksi transfer harus diatas Rp.50000");
        }
        else
        {
            gethasil();
            JOptionPane.showMessageDialog(null, "berhasil");
            
            this.dispose();
            new Home().setVisible(true);
        }
    }
        else{
            JOptionPane.showMessageDialog(null,"Saldo anda kurang dari Rp.50000");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void norekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_norekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField norek;
    // End of variables declaration//GEN-END:variables

    public int gethasil() {
        
        hasil = saldo1 -= b ;
    
        return hasil ;
    }

}
